### ISSUE TITLE
POST sample string reference error

### ISSUE THREAD

**Issue by TcT2k** [JosephP91/curlcpp#57]
In the post sample this line uses the "user" constant, but in curl_pair the value is a reference:
`
curl_pair<CURLformoption,string> name_form(CURLFORM_COPYNAME,"user");
`

It only works when changed like this because of the scope of the string:
`
std::string fieldName = "user";
curl_pair<CURLformoption,string> name_form(CURLFORM_COPYNAME, fieldName);
`

Maybe `curl_pair` should copy the value? But at least the sample should be changed.

**Comment by JosephP91** [comment]
Hi @TcT2k !
another user found this issue, but I thought it was solved https://github.com/JosephP91/curlcpp/issues/18
Can you show me your code example? Thank you!

**Comment by wise86-android** [comment]
I think that as the last comment on issue #18  say the problem is that you are keeping a reference to a temporary object (the string that is create when you pass a const char* to a function that require a string).
you have 2 option:
  1 - use a constructor with an RValue (as write in issue #18)
  2 - accept a string and not a string reference for force the compiler to copy it, and then move the string inside the pair class. 

@TcT2k try if this commit fix the problem: https://github.com/wise86-android/curlcpp/commit/be680229044a347d324a2c49466c1f3e1a59bbc3

**Comment by JosephP91** [comment]
@TcT2k is this issue solved?

**Comment by JosephP91** [comment]
@TcT2k any news?
